name: Update Tasks Text Files

on:
  push:
    paths:
      - '**.csv'

jobs:
  update_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Use the latest version if available

      - name: Set up Python
        uses: actions/setup-python@v3  # Use the latest version if available
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run script to update text files
        run: python scripts/update_tasks.py

      - name: Check for file changes
        id: git-check
        run: echo ::set-output name=status::$(git status --porcelain)

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add ./scripts/*.txt index.html ./scripts/server-list.json
          git commit -m "Update tasks text files" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
        if: steps.git-check.outputs.status != ''
